# Generated by Django 5.1.7 on 2025-04-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
    ]
