# Generated by Django 4.2.19 on 2025-05-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='header_image',
        ),
    ]
